### PR TITLE
Update RLL version

### PR DESCRIPTION
**Pull request by leetfin**
### Description of the changes

Fix bug discussed in coding channel :P

### Have the changes in this PR been tested?

Yes

### CODE REVIEW

**Comment by Jackenmen** [comment]
Wrong base?

**Comment by leetfin** [comment]
Yup, sorry about that!

**Comment by Jackenmen** [comment]
This commit will disappear whenever I rebase all of these changes on top of V3/dev (which has to wait until I make another PR that's related to project's packaging) but until then, it makes sense to allow people to continue to use it, even if the deps are tad outdated, thanks 👍

**Comment by leetfin** [comment]
Thanks for helping me figure this one out!

**Pull request merged**
